version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=uroot
      - POSTGRES_PASSWORD=qwertyui
      - POSTGRES_DB=userdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  db-data: